name:                grpc-etcd-client
version:             0.1.2.1
github:              "lucasdicioccio/grpc-etcd-client"
license:             BSD3
author:              "Lucas DiCioccio"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2018 Lucas DiCioccio"
homepage:       https://github.com/lucasdicioccio/etcd-grpc#readme
bug-reports:    https://github.com/lucasdicioccio/etcd-grpc/issues
github:         lucasdicioccio/etcd-grpc

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            gRPC client for etcd
category:            Distributed Computing

description:         Please see the README on GitHub at <https://github.com/lucasdicioccio/etcd-grpc#readme>

dependencies:
- base >= 4.11 && < 5
- bytestring >= 0.10 && < 0.11
- grpc-api-etcd == 0.2.0.0
- http2-client >= 0.8 && < 0.9
- http2-client-grpc >= 0.5.0.4 && < 0.6
- lens >= 4.16 && < 4.18
- network >= 2.6 && < 2.9
- proto-lens >= 0.4 && < 0.5
- proto-lens-runtime >= 0.4 && < 0.5

default-extensions:
- DataKinds
- OverloadedStrings

library:
  source-dirs: src
